# Generated by Django 4.2.6 on 2023-10-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cart/gift')),
            ],
        ),
    ]
